export const REQUEST_USER_TOKEN_TO_SPRING = 'REQUEST_USER_TOKEN_TO_SPRING'
export const REQUEST_USER_INFO_TO_SPRING = 'REQUEST_USER_INFO_TO_SPRING'
export const REQUEST_IS_LOGIN_TO_SPRING = 'REQUEST_IS_LOGIN_TO_SPRING'