export const REQUEST_USER_TOKEN_TO_SPRING = 'REQUEST_USER_TOKEN_TO_SPRING'
export const REQUEST_USER_INFO_TO_SPRING = 'REQUEST_USER_INFO_TO_SPRING'
export const REQUEST_MEMBER_LIST_TO_SPRING = 'REQUEST_MEMBER_LIST_TO_SPRING'
export const REQUEST_MEMBER_TO_SPRING = 'REQUEST_MEMBER_TO_SPRING'